config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :posts
  end
  resources :games do
    resources :characters
  end

  root "games#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :game

  validates :name, presence: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/game.rb
class Game < ActiveRecord::Base

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_many :posts,  dependent: :destroy
	has_many :characters,  dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :game
	validates :content, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

def create
    @game = Game.find(params[:game_id])
    @character = @game.characters.create(character_params)
    if @character.save
       
       flash[:success] = "Saved!"
        redirect_to game_path(@game)      
      else
        flash[:alert] = "Could not save client"
        redirect_to @game
      end
  end

  def edit
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:id])
  end

  def update
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:id])
 
    if @character.update(character_params)
      redirect_to @game
    else
      render 'edit'
    end
  end

  def destroy
      @game = Game.find(params[:game_id])
      @character = @game.characters.find(params[:id])
      @character.destroy
      redirect_to game_path(@game)
    end
 
  private
    def character_params
      params.require(:character).permit(:name, :bio, :image)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @post = Post.new
    @character = Character.new
    
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
    @post = Post.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @post = Post.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
  	@game = Game.find(params[:game_id])
    @post = @game.posts.create(post_params)

   
      if @post.save
       
       flash[:success] = "Saved!"
        redirect_to game_path(@game)      
      else
        flash[:alert] = "Could not save client"
        redirect_to @game
      end
    end

    def destroy
      @game = Game.find(params[:game_id])
      @post = @game.posts.find(params[:id])
      @post.destroy
      redirect_to game_path(@game)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/characters/_character.html.erb
<div class = "game-content">
	<div class = "row">
		<div class = "col-md-2 post">
			<%= image_tag character.image.url %>
			<%= link_to 'Delete', [character.game, character],
		               method: :delete, 
		               data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-block" %>
		    <%= link_to 'Edit', edit_game_character_path(character.game, character), class: "btn btn-primary btn-block" %>
		</div>
		<div class = "col-md-10">
			<p>
			  <h2><%= character.name %></h2>
			</p>
			 
			<p>
			  <strong>Notes:</strong>
			  <%= character.bio %>
			</p>
			
		</div>
	</div>
</div>

app/views/characters/_form.html.erb
<div class = "form-group">
  <%= form_for [@game, @character] do |f| %>
    <p>
      <%= f.text_field :name ,class: "form-control", placeholder: "Name" %>
    </p>
    <p>
      <%= f.text_area :bio , class: "form-control", placeholder: "Notes" %>
    </p>
    <%= f.label :image , class: "form-control" %>
      <%= f.file_field :image, class: "form-control" %>
    <p>
      <%= f.submit class: "btn btn-primary btn-block" %>
    </p>
  <% end %>
</div>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class = "form-group">
    <div class="field">
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      <%= f.file_field :image, class: "form-control" %>
    </div>


    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>
<div >
	<div class = "well well-sm"><h3>My Games</h3></div>
		<div class = "row">
			<div class = " col-md-3">
				<div onclick="location.href=' /games/new';" style="cursor: pointer;" class="game">
					<h1 class = "text-center"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></h1>
				</div>
			</div>
		    <% @games.each do |game| %>
		    <div class = "col-md-3">
		    	
		    		<div class = "game text-center">
				      <p class = "game-text"><%= link_to game.title, game %></p>  
				        <%= link_to 'Edit', edit_game_path(game), class: "btn btn-primary btn-sm" %>
				        <%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %> 
				    </div> <!-- /game -->
		     </div> <!-- /col-md-3 -->
		    <% end %>

		</div> <!-- /row -->
	<br>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<div >
	<div class = "row ">
		<div class = "col-md-12 cover-img">
			<div class = "layer"></div>
			<%= image_tag @game.image.url %>
		</div>
	</div>

	<div class = "row">
		<div class = "col-md-12">
			<h3><%= @game.title %>
			<%= link_to 'Edit', edit_game_path(@game), class: "btn btn-primary" %>
			<%= link_to 'Back', games_path, class: "btn btn-primary"  %></h3>
		</div>
	</div>

	<div class = "row">
		<div class= "col-md-12" >
			<ul class="nav nav-tabs nav-justified" role="tablist">
			    <li role="presentation" class="active"><a href="#entries" aria-controls="entries" role="tab" data-toggle="tab">Entries</a></li>
			    <li role="presentation"><a href="#characters" aria-controls="characters" role="tab" data-toggle="tab">Characters</a></li>
			    <li role="presentation"><a href="#lore" aria-controls="lore" role="tab" data-toggle="tab">Lore</a></li>
			    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
		  </ul>
		<div class="tab-content game-content">
		    <div role="tabpanel" class="tab-pane active" id="entries">
		    	<%= render "posts/form" %>
		    	<%= render @game.posts %>
		    </div>
		    <div role="tabpanel" class="tab-pane" id="characters">
		    	<%= render "characters/form" %>
		    	<%= render @game.characters %>

		    </div>
		    <div role="tabpanel" class="tab-pane" id="lore"><p>Lore</p></div>
		    <div role="tabpanel" class="tab-pane" id="settings">...</div>
		  </div> <!-- tab-content -->
		  	
		</div>	<!-- div-nav-tabs -->
	</div><!-- row -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameJournal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = "container">
		<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

		<div class = "center-div screen">
			<div class= "navbar"> 
				<%= link_to "Home", root_path, class: "btn navbar-brand" %>

			</div>
			<%= yield %>
			<nav class="navbar navbar-default navbar-fixed-bottom">
  				<div class="container">
			    <a href="#" id="font-link">Change font! </a>
			  	</div>
			</nav>
		</div>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@game, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class = "form-group">
    <div class="field">
      <%= f.text_area :content, class: "form-control" , placeholder: "Tell us what you did!" %>
    </div>
  </div>  
      <%= f.submit class: "btn btn-primary form-control" %>
  <% end %>

app/views/posts/_post.html.erb
<div class = "game-content">
	<div class = "row">
		<div class= "col-md-2 post">
			<h2 class="text-center"><%= post.created_at.strftime("%b") %><br>
			<%= post.created_at.strftime("%d") %></h2>

				<%= link_to 'Delete', [post.game, post],
		               method: :delete, 
		               data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-block" %>
			</div>
		
		<div class = "col-md-10">
			<p><%= post.content %>
			</p>
		</div>
	</div>	
</div>